apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  selector:
    app: member-service
  ports:
  - protocol: TCP
    port: 50052        # 클러스터 내부에서 접근할 포트
    targetPort: 50052  # 컨테이너 내부 포트
  type: ClusterIP       # 클러스터 내부 통신
