// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: history-service/history/history.proto

package history

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level  string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	QuizId int64  `protobuf:"varint,3,opt,name=quizId,proto3" json:"quizId,omitempty"`
}

func (x *SaveHistoryRequest) Reset() {
	*x = SaveHistoryRequest{}
	mi := &file_history_service_history_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHistoryRequest) ProtoMessage() {}

func (x *SaveHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_service_history_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHistoryRequest.ProtoReflect.Descriptor instead.
func (*SaveHistoryRequest) Descriptor() ([]byte, []int) {
	return file_history_service_history_history_proto_rawDescGZIP(), []int{0}
}

func (x *SaveHistoryRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SaveHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveHistoryRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

type SaveHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveHistoryResponse) Reset() {
	*x = SaveHistoryResponse{}
	mi := &file_history_service_history_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHistoryResponse) ProtoMessage() {}

func (x *SaveHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_history_service_history_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHistoryResponse.ProtoReflect.Descriptor instead.
func (*SaveHistoryResponse) Descriptor() ([]byte, []int) {
	return file_history_service_history_history_proto_rawDescGZIP(), []int{1}
}

type GetAllHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetAllHistoryRequest) Reset() {
	*x = GetAllHistoryRequest{}
	mi := &file_history_service_history_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHistoryRequest) ProtoMessage() {}

func (x *GetAllHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_service_history_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetAllHistoryRequest) Descriptor() ([]byte, []int) {
	return file_history_service_history_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAllHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizIds []int64 `protobuf:"varint,1,rep,packed,name=quizIds,proto3" json:"quizIds,omitempty"`
}

func (x *GetAllHistoryResponse) Reset() {
	*x = GetAllHistoryResponse{}
	mi := &file_history_service_history_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHistoryResponse) ProtoMessage() {}

func (x *GetAllHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_history_service_history_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetAllHistoryResponse) Descriptor() ([]byte, []int) {
	return file_history_service_history_history_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllHistoryResponse) GetQuizIds() []int64 {
	if x != nil {
		return x.QuizIds
	}
	return nil
}

var File_history_service_history_history_proto protoreflect.FileDescriptor

var file_history_service_history_history_proto_rawDesc = []byte{
	0x0a, 0x25, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x22, 0x5a, 0x0a, 0x12, 0x73, 0x61, 0x76, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x71, 0x75, 0x69, 0x7a, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x71, 0x75, 0x69, 0x7a, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13,
	0x73, 0x61, 0x76, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x71, 0x75, 0x69, 0x7a, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x71,
	0x75, 0x69, 0x7a, 0x49, 0x64, 0x73, 0x32, 0xa3, 0x01, 0x0a, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x48, 0x0a, 0x0b, 0x73, 0x61, 0x76, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x1b, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x73, 0x61, 0x76, 0x65,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d,
	0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1d, 0x2e,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x38, 0x5a, 0x36,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2d,
	0x63, 0x6f, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_history_service_history_history_proto_rawDescOnce sync.Once
	file_history_service_history_history_proto_rawDescData = file_history_service_history_history_proto_rawDesc
)

func file_history_service_history_history_proto_rawDescGZIP() []byte {
	file_history_service_history_history_proto_rawDescOnce.Do(func() {
		file_history_service_history_history_proto_rawDescData = protoimpl.X.CompressGZIP(file_history_service_history_history_proto_rawDescData)
	})
	return file_history_service_history_history_proto_rawDescData
}

var file_history_service_history_history_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_history_service_history_history_proto_goTypes = []any{
	(*SaveHistoryRequest)(nil),    // 0: history.saveHistoryRequest
	(*SaveHistoryResponse)(nil),   // 1: history.saveHistoryResponse
	(*GetAllHistoryRequest)(nil),  // 2: history.getAllHistoryRequest
	(*GetAllHistoryResponse)(nil), // 3: history.getAllHistoryResponse
}
var file_history_service_history_history_proto_depIdxs = []int32{
	0, // 0: history.History.saveHistory:input_type -> history.saveHistoryRequest
	2, // 1: history.History.getAllHistory:input_type -> history.getAllHistoryRequest
	1, // 2: history.History.saveHistory:output_type -> history.saveHistoryResponse
	3, // 3: history.History.getAllHistory:output_type -> history.getAllHistoryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_history_service_history_history_proto_init() }
func file_history_service_history_history_proto_init() {
	if File_history_service_history_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_history_service_history_history_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_history_service_history_history_proto_goTypes,
		DependencyIndexes: file_history_service_history_history_proto_depIdxs,
		MessageInfos:      file_history_service_history_history_proto_msgTypes,
	}.Build()
	File_history_service_history_history_proto = out.File
	file_history_service_history_history_proto_rawDesc = nil
	file_history_service_history_history_proto_goTypes = nil
	file_history_service_history_history_proto_depIdxs = nil
}
