# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: member.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'member.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmember.proto\x12\x06member\"8\n\x06Member\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"5\n\x13\x43reateMemberRequest\x12\x1e\n\x06member\x18\x01 \x01(\x0b\x32\x0e.member.Member\"_\n\x13UpdateMemberRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x14\n\x0cold_password\x18\x04 \x01(\t\">\n\x13\x44\x65leteMemberRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x05\x12\x14\n\x0cold_password\x18\x02 \x01(\t\"\'\n\x14\x43reateMemberResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x14UpdateMemberResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteMemberResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x17GetMemberByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"-\n\x18GetMemberByEmailResponse\x12\x11\n\tmember_id\x18\x01 \x01(\x05\x32\xc7\x02\n\rMemberService\x12I\n\x0c\x43reateMember\x12\x1b.member.CreateMemberRequest\x1a\x1c.member.CreateMemberResponse\x12I\n\x0cUpdateMember\x12\x1b.member.UpdateMemberRequest\x1a\x1c.member.UpdateMemberResponse\x12I\n\x0c\x44\x65leteMember\x12\x1b.member.DeleteMemberRequest\x1a\x1c.member.DeleteMemberResponse\x12U\n\x10GetMemberByEmail\x12\x1f.member.GetMemberByEmailRequest\x1a .member.GetMemberByEmailResponseB6Z4github.com/mail-cote/go-server/member-service/memberb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'member_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/mail-cote/go-server/member-service/member'
  _globals['_MEMBER']._serialized_start=24
  _globals['_MEMBER']._serialized_end=80
  _globals['_CREATEMEMBERREQUEST']._serialized_start=82
  _globals['_CREATEMEMBERREQUEST']._serialized_end=135
  _globals['_UPDATEMEMBERREQUEST']._serialized_start=137
  _globals['_UPDATEMEMBERREQUEST']._serialized_end=232
  _globals['_DELETEMEMBERREQUEST']._serialized_start=234
  _globals['_DELETEMEMBERREQUEST']._serialized_end=296
  _globals['_CREATEMEMBERRESPONSE']._serialized_start=298
  _globals['_CREATEMEMBERRESPONSE']._serialized_end=337
  _globals['_UPDATEMEMBERRESPONSE']._serialized_start=339
  _globals['_UPDATEMEMBERRESPONSE']._serialized_end=378
  _globals['_DELETEMEMBERRESPONSE']._serialized_start=380
  _globals['_DELETEMEMBERRESPONSE']._serialized_end=419
  _globals['_GETMEMBERBYEMAILREQUEST']._serialized_start=421
  _globals['_GETMEMBERBYEMAILREQUEST']._serialized_end=461
  _globals['_GETMEMBERBYEMAILRESPONSE']._serialized_start=463
  _globals['_GETMEMBERBYEMAILRESPONSE']._serialized_end=508
  _globals['_MEMBERSERVICE']._serialized_start=511
  _globals['_MEMBERSERVICE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
