# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import member_pb2 as member__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in member_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemberServiceStub(object):
    """Member Service 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMember = channel.unary_unary(
                '/member.MemberService/CreateMember',
                request_serializer=member__pb2.CreateMemberRequest.SerializeToString,
                response_deserializer=member__pb2.CreateMemberResponse.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/member.MemberService/UpdateMember',
                request_serializer=member__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=member__pb2.UpdateMemberResponse.FromString,
                _registered_method=True)
        self.DeleteMember = channel.unary_unary(
                '/member.MemberService/DeleteMember',
                request_serializer=member__pb2.DeleteMemberRequest.SerializeToString,
                response_deserializer=member__pb2.DeleteMemberResponse.FromString,
                _registered_method=True)
        self.GetMemberByEmail = channel.unary_unary(
                '/member.MemberService/GetMemberByEmail',
                request_serializer=member__pb2.GetMemberByEmailRequest.SerializeToString,
                response_deserializer=member__pb2.GetMemberByEmailResponse.FromString,
                _registered_method=True)
        self.GetAllMember = channel.unary_unary(
                '/member.MemberService/GetAllMember',
                request_serializer=member__pb2.GetAllMemberRequest.SerializeToString,
                response_deserializer=member__pb2.GetAllMemberResponse.FromString,
                _registered_method=True)


class MemberServiceServicer(object):
    """Member Service 정의
    """

    def CreateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemberByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=member__pb2.CreateMemberRequest.FromString,
                    response_serializer=member__pb2.CreateMemberResponse.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=member__pb2.UpdateMemberRequest.FromString,
                    response_serializer=member__pb2.UpdateMemberResponse.SerializeToString,
            ),
            'DeleteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMember,
                    request_deserializer=member__pb2.DeleteMemberRequest.FromString,
                    response_serializer=member__pb2.DeleteMemberResponse.SerializeToString,
            ),
            'GetMemberByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemberByEmail,
                    request_deserializer=member__pb2.GetMemberByEmailRequest.FromString,
                    response_serializer=member__pb2.GetMemberByEmailResponse.SerializeToString,
            ),
            'GetAllMember': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMember,
                    request_deserializer=member__pb2.GetAllMemberRequest.FromString,
                    response_serializer=member__pb2.GetAllMemberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'member.MemberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('member.MemberService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemberService(object):
    """Member Service 정의
    """

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/CreateMember',
            member__pb2.CreateMemberRequest.SerializeToString,
            member__pb2.CreateMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/UpdateMember',
            member__pb2.UpdateMemberRequest.SerializeToString,
            member__pb2.UpdateMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/DeleteMember',
            member__pb2.DeleteMemberRequest.SerializeToString,
            member__pb2.DeleteMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemberByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/GetMemberByEmail',
            member__pb2.GetMemberByEmailRequest.SerializeToString,
            member__pb2.GetMemberByEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/member.MemberService/GetAllMember',
            member__pb2.GetAllMemberRequest.SerializeToString,
            member__pb2.GetAllMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
