apiVersion: v1
kind: Service
metadata:
  name: history-service
  labels:
    app: history-service
spec:
  selector:
    app: history-service
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 9001